FROM python:3.9-slim-buster

RUN apt-get update

# install native dependencies
RUN apt-get install -y --no-install-recommends \
  make \
  gcc \
  g++ \
  zlib1g-dev \
  python3-dev \
  libbz2-dev \
  liblzma-dev

RUN pip install numpy==1.19.4 scipy==1.5.4 cython==0.29.21
RUN pip install pysam==0.16 dinopy==2.2.0 simlord

WORKDIR /usr/app

ENTRYPOINT [ "python", "-m", "python.simulate" ]
