FROM python:3.9-slim-buster

RUN apt-get update

# install native dependencies
RUN apt-get install -y --no-install-recommends \
  make \
  gcc \
  g++ \
  zlib1g-dev \
  python3-dev \
  libbz2-dev \
  liblzma-dev

WORKDIR /usr/app

RUN touch __init__.py

COPY requirements.txt quality/requirements.txt

RUN pip install -r quality/requirements.txt

ENTRYPOINT [ "python", "-m", "quality" ]
